[package]
name = "cdby"
version = "0.0.1"
edition = "2021"

[dependencies]
nix="0.26.2"
regex = "1"
ignore = "0.4"

[dependencies.clap]
version = "4.1.4"
features = ["suggestions", "color", "wrap_help", "cargo", "unstable-grouped", "derive"]

[[bin]]
bench = false
path = "src/main.rs"
name = "cdby"